package utils

const BaseURL = "https://api.mangadex.org"
const CoverURL = "https://uploads.mangadex.org/covers"
const KitsuBaseURL = "https://kitsu.io/api/edge"
const MALBaseURL = "https://api.myanimelist.net/v2"
const BearerToken = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjJjMWNmMTM0ZmZjYzNjN2UzYTgwNjE1MjVkNzU4NmIxMmRhNzgzYzlmMzZjODdhMGI0NzUwMzcxNTBkMTEzMzk3YjMyZTUxMGEwZTRiMDdlIn0.eyJhdWQiOiIyNTNlZThkYzk2ODdjOGQ2MDhlMjlhYmMyODMyODc0OCIsImp0aSI6IjJjMWNmMTM0ZmZjYzNjN2UzYTgwNjE1MjVkNzU4NmIxMmRhNzgzYzlmMzZjODdhMGI0NzUwMzcxNTBkMTEzMzk3YjMyZTUxMGEwZTRiMDdlIiwiaWF0IjoxNzA0MTQ0Nzk5LCJuYmYiOjE3MDQxNDQ3OTksImV4cCI6MTcwNjgyMzE5OSwic3ViIjoiMTc2NDA1NDUiLCJzY29wZXMiOltdfQ.UdZHpzuule4X2KPwm2UMMpUFX8Xl9wyUEC4NTPfqFfYcly-kcua_2opRqpD6JRMcVHW33XHlF_cPPyxUOUxjpc2shG5o8vPKN1fl8SqRmjLB8KoSfAY2-0EMHAFgBJqklgW7K0g_JUSf63hYVvBRwlNzlIsklfYM1-1S7DzntUVruNij54Qnd5tCrYuop2DGXdzkLtU_CNQTgaVS5cdUWvVRxajHzGkd8hP5rT0f0DbhoNlJDPeAMV2EAJG5w5OEcDZ9kXj_vYYnwoAO4FirGxcsKUsRY0QVNNufSrT4E-bhzVBBu1siDBpEGVT7G01r1nI4Fg6T3y7Toee8VWBxeA"
const MALMangaDetailsField = "id,title,main_picture,alternative_titles,start_date,end_date,synopsis,mean,rank,popularity,num_list_users,num_scoring_users,nsfw,created_at,updated_at,media_type,status,genres,my_list_status,num_volumes,num_chapters,authors{first_name,last_name},pictures,background,related_anime,related_manga,recommendations,serialization{name}"
const MALUserDetailsField = "anime_statistics"
